# Fix terminal colors
set -g default-terminal "tmux-256color"

set -g status-interval 1

set -g allow-passthrough

# Prefix key
set-option -g prefix C-o
bind-key C-o send-prefix

bind-key "t" run-shell "sesh connect \"$(sesh list | fzf-tmux -p 55%,60%)\""
bind-key "b" set -g status

# set -g status

# Copy mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Create a new blank session
bind C-n new-session -c "$(pwd)" -s "blank"

# Reload config (prefix-r)
bind r source-file ~/.dotfiles/nixos/nixos/features/tmux/tmux.conf

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

# Window start index
set -g base-index 1

# Don't detach from sessions on exit
set -g detach-on-destroy off

# Renumber windows on changes
set -g renumber-windows on

# Disable auto window naming
set-option -g allow-rename off 

# Vi motions
setw -g mode-keys vi

# Pane border color
set -g pane-border-style fg='#282727'
set -g pane-active-border-style fg='#ffffff'

# Status bar
set -g status-left-length 50
